-- codex-weaponskill.lua
-- Date: 2025‑11‑02
-- Sources: BG Wiki, FFXIclopedia, FFXIAH, BlueGartr/Windower

local WEAPON_SKILLS = {

  sword = {
    ["Savage Blade"] = {
      hits = 2,
      class = "physical",
      ftp = {4.00, 10.25, 13.75},
      ftp_rep = false,
      wsc = { STR = 0.50, MND = 0.50 },
      sc = {"Fragmentation", "Scission"},
    },
    ["Chant du Cygne"] = {
      hits = 3,
      class = "physical",
      ftp = {1.25, 1.25, 1.25},
      ftp_rep = true,
      wsc = { DEX = 0.80 },
      crit_rate = {0.10, 0.25, 0.40},
      sc = {"Light", "Detonation"},
    },
    ["Expiacion"] = {
      hits = 2,
      class = "physical",
      ftp = {3.796875, 9.390625, 12.1875},
      ftp_rep = false,
      wsc = { STR = 0.30, DEX = 0.20, INT = 0.30 },
      sc = {"Distortion", "Scission"},
    },
    ["Requiescat"] = {
      hits = 5,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = true,
      wsc = { MND = 0.80 },
      sc = {"Darkness", "Gravitation", "Scission"},
    },
    ["Fast Blade"] = {
      hits = 2,
      class = "physical",
      ftp = {1.00, 3.00, 5.00},
      ftp_rep = false,
      wsc = { STR = 0.40, DEX = 0.40 },
      sc = {"Scission"},
    },
    ["Burning Blade"] = {
      hits = 2,
      class = "physical",
      element = "Fire",
      dstat = "INT",
      ftp = {1.00, 3.00, 5.00},
      ftp_rep = false,
      wsc = { STR = 0.40, INT = 0.40 },
      sc = {"Liquefaction"},
    },
    ["Red Lotus Blade"] = {
      hits = 2,
      class = "physical",
      element = "Fire",
      dstat = "INT",
      ftp = {1.00, 3.00, 5.00},
      ftp_rep = false,
      wsc = { STR = 0.40, INT = 0.40 },
      sc = {"Liquefaction", "Detonation"},
    },
    ["Vorpal Blade"] = {  -- newly verified
      hits = 4,
      class = "physical",
      ftp = {1.375, 1.375, 1.375},  -- value from BG Wiki :contentReference[oaicite:0]{index=0}
      ftp_rep = false,
      wsc = { STR = 0.60 },
      sc = {"Scission", "Impaction"},
    },
  },

  great_sword = {
    ["Resolution"] = {
      hits = 5,
      class = "physical",
      ftp = {2.00, 2.00, 2.00},
      ftp_rep = true,
      wsc = { STR = 0.85 },
      sc = {"Scission", "Resolution"},
    },
    ["Torcleaver"] = {
      hits = 1,
      class = "physical",
      ftp = {4.75, 7.00, 10.25},
      ftp_rep = false,
      wsc = { VIT = 0.80 },
      sc = {"Light", "Compression"},
    },
  },

  dagger = {
    ["Evisceration"] = {
      hits = 5,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = true,
      wsc = { DEX = 0.80 },
      sc = {"Gravitation", "Transfixion"},
    },
    ["Rudra's Storm"] = {
      hits = 1,
      class = "physical",
      ftp = {3.00, 7.00, 13.00},
      ftp_rep = false,
      wsc = { DEX = 1.00 },
      sc = {"Light", "Scission"},
    },
    ["Exenterator"] = {
      hits = 4,
      class = "physical",
      ftp = {1.1875, 1.1875, 1.1875},
      ftp_rep = true,
      wsc = { AGI = 0.85 },
      sc = {"Light", "Fragmentation", "Scission"},
    },
    ["Dancing Edge"] = {
      hits = 5,
      class = "physical",
      ftp = {1.1875, 1.1875, 1.1875},
      ftp_rep = false,
      wsc = { DEX = 0.40, CHR = 0.40 },
      sc = {"Scission", "Detonation"},
    },
    ["Shark Bite"] = {
      hits = 2,
      class = "physical",
      ftp = {4.50, 6.80, 8.50},
      ftp_rep = false,
      wsc = { DEX = 0.40, AGI = 0.40 },
      sc = {"Fragmentation"},
    },
    ["Mercy Stroke"] = {
      hits = 1,
      class = "physical",
      ftp = {5.00, 5.00, 5.00},
      ftp_rep = false,
      wsc = { STR = 0.80 },
      sc = {"Darkness", "Gravitation"},
    },
  },

  katana = {
    ["Blade: Hi"] = {
      hits = 1,
      class = "physical",
      ftp = {3.50, 3.50, 3.50},
      ftp_rep = false,
      wsc = { DEX = 0.80 },
      crit_rate = {0.10, 0.25, 0.40},
      sc = {"Light", "Transfixion"},
    },
    ["Blade: Shun"] = {
      hits = 5,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = true,
      wsc = { DEX = 0.85 },
      sc = {"Light", "Fusion", "Impaction"},
    },
    ["Blade: Rin"] = {
      hits = 2,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.60, DEX = 0.20 },
      sc = {"Scission"},
    },
    ["Blade: Retsu"] = {
      hits = 2,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.20, DEX = 0.60 },
      sc = {"Detonation"},
    },
    ["Blade: Teki"] = {
      hits = 2,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.30, INT = 0.30 },
      sc = {"Transfixion"},
    },
  },

  great_katana = {
    ["Tachi: Fudo"] = {
      hits = 1,
      class = "physical",
      ftp = {4.50, 7.50, 9.50},
      ftp_rep = false,
      wsc = { STR = 0.80 },
      sc = {"Light", "Fragmentation"},
    },
    ["Tachi: Shoha"] = {
      hits = 2,
      class = "physical",
      ftp = {3.00, 4.50, 6.00},
      ftp_rep = false,
      wsc = { STR = 0.85 },
      sc = {"Fragmentation", "Detonation"},
    },
    ["Tachi: Kasha"] = {
      hits = 1,
      class = "physical",
      ftp = {1.5625, 2.6875, 4.125},
      ftp_rep = false,
      wsc = { STR = 0.75 },
      sc = {"Fusion", "Compression"},
    },
    ["Tachi: Kaiten"] = {
      hits = 1,
      class = "physical",
      ftp = {3.00, 4.00, 5.00},
      ftp_rep = false,
      wsc = { STR = 0.80 },
      sc = {"Light", "Fragmentation"},
    },
    ["Tachi: Enpi"] = {
      hits = 2,
      class = "physical",
      ftp = {1.00, 2.00, 4.00},
      ftp_rep = false,
      wsc = { STR = 0.60 },
      sc = {"Transfixion", "Scission"},
    },
  },

  great_axe = {
    ["Upheaval"] = {
      hits = 4,
      class = "physical",
      ftp = {1.50, 2.50, 3.50},
      ftp_rep = true,
      wsc = { VIT = 0.80 },
      sc = {"Fusion", "Impaction"},
    },
    ["Ukko's Fury"] = {
      hits = 2,
      class = "physical",
      ftp = {2.00, 2.75, 4.00},
      ftp_rep = false,
      wsc = { STR = 0.80 },
      crit_rate = {0.20, 0.35, 0.50},
      sc = {"Light", "Detonation"},
    },
  },

  axe = {
    ["Ruinator"] = {
      hits = 4,
      class = "physical",
      ftp = {2.00, 2.00, 2.00},
      ftp_rep = true,
      wsc = { STR = 0.85 },
      sc = {"Gravitation", "Scission"},
    },
    ["Decimation"] = {
      hits = 3,
      class = "physical",
      ftp = {1.75, 1.75, 1.75},
      ftp_rep = true,
      wsc = { STR = 0.50, DEX = 0.50 },
      sc = {"Fusion", "Detonation"},
    },
    ["Smash Axe"] = {
      hits = 2,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 1.00 },
      sc = {"Impaction"},
    },
    ["Raging Axe"] = {
      hits = 2,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.60 },
      sc = {"Scission"},
    },
    ["Gale Axe"] = {
      hits = 1,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 1.00 },
      sc = {"Detonation"},
    },
    ["Rampage"] = {  -- newly verified
      hits = 5,
      class = "physical",
      ftp = {0.50, 0.50, 0.50},  -- approximate; source indicates STR 50% :contentReference[oaicite:1]{index=1}
      ftp_rep = false,
      wsc = { STR = 0.50 },
      sc = {"Scission"},
    },
  },

  scythe = {
    ["Resolution (Scythe)"] = {
      hits = 5,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = true,
      wsc = { STR = 0.60, INT = 0.60 },
      sc = {"Gravitation", "Compression"},
    },
    ["Insurgency"] = {
      hits = 4,
      class = "physical",
      ftp = {2.00, 2.00, 2.00},
      ftp_rep = true,
      wsc = { STR = 0.30, INT = 0.30 },
      sc = {"Darkness", "Compression"},
    },
    ["Cross Reaper"] = {
      hits = 2,
      class = "physical",
      ftp = {3.25, 3.25, 3.25},
      ftp_rep = false,
      wsc = { STR = 0.60, INT = 0.60 },
      sc = {"Darkness", "Scission"},
    },
    ["Entropy"] = {
      hits = 4,
      class = "physical",
      ftp = {0.75, 1.25, 2.00},
      ftp_rep = true,
      wsc = { INT = 0.85 },
      sc = {"Darkness", "Gravitation", "Reverberation"},
    },
    ["Dark Harvest"] = {
      hits = 1,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.40, INT = 0.40 },
      sc = {"Darkness"},
    },
    ["Guillotine"] = {  -- newly verified
      hits = 4,
      class = "physical",
      ftp = {0.875, 0.875, 0.875},  -- from BG Wiki :contentReference[oaicite:2]{index=2}
      ftp_rep = false,
      wsc = { STR = 0.30, MND = 0.50 },  -- note: BG Wiki lists 50% MND / 30% STR :contentReference[oaicite:3]{index=3}
      sc = {"Induration"},
    },
  },

  polearm = {
    ["Stardiver"] = {
      hits = 4,
      class = "physical",
      ftp = {0.75, 0.75, 0.75},
      ftp_rep = true,
      wsc = { STR = 0.60 },
      sc = {"Gravitation", "Transfixion"},
    },
    ["Camlann's Torment"] = {
      hits = 1,
      class = "physical",
      ftp = {4.00, 7.00, 10.00},
      ftp_rep = false,
      wsc = { VIT = 0.80 },
      sc = {"Light", "Scission"},
    },
  },

  hand_to_hand = {
    ["Victory Smite"] = {
      hits = 4,
      class = "physical",
      ftp = {2.25, 2.25, 2.25},
      ftp_rep = true,
      wsc = { STR = 0.80 },
      crit_rate = {0.15, 0.30, 0.45},
      sc = {"Light", "Compression"},
    },
    ["Howling Fist"] = {
      hits = 2,
      class = "physical",
      ftp = {2.75, 4.50, 6.25},
      ftp_rep = false,
      wsc = { STR = 0.60, VIT = 0.60 },
      sc = {"Gravitation", "Impaction"},
    },
    ["Spinning Attack"] = {
      hits = 2,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = true,
      wsc = { STR = 1.00 },
      sc = {"Liquefaction", "Impaction"},
    },
    ["Dragon Kick"] = {
      hits = 2,
      class = "physical",
      ftp = {2.00, 2.75, 3.50},
      ftp_rep = false,
      wsc = { STR = 0.50, DEX = 0.50 },
      sc = {"Fragmentation"},
    },
    ["Tornado Kick"] = {
      hits = 3,
      class = "physical",
      ftp = {1.70, 2.80, 4.50},
      ftp_rep = false,
      wsc = { STR = 0.40, VIT = 0.40 },
      sc = {"Induration", "Impaction", "Detonation"},
    },
    ["Asuran Fists"] = {
      hits = 8,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.15, VIT = 0.15 },
      sc = {"Gravitation", "Liquefaction"},
    },
    ["Backhand Blow"] = {
      hits = 1,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.50, DEX = 0.50 },
      sc = {"Detonation"},
    },
    ["One Inch Punch"] = {
      hits = 1,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { VIT = 1.00 },
      sc = {"Compression"},
    },
    ["Raging Fists"] = {
      hits = 5,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.30, DEX = 0.30 },
      sc = {"Impaction"},
    },
    ["Final Heaven"] = {
      hits = 8,
      class = "physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.15, VIT = 0.15 },
      sc = {"Light"},
    },
  },

  club = {
    ["Judgment"] = {
      hits = 1,
      class = "physical",
      ftp = {3.00, 6.25, 8.75},
      ftp_rep = false,
      wsc = { STR = 0.60, MND = 0.60 },
      sc = {"Fusion", "Impaction"},
    },
    ["Realmrazer"] = {
      hits = 7,
      class = "physical",
      ftp = {0.83, 0.83, 0.83},
      ftp_rep = true,
      wsc = { MND = 0.85 },
      sc = {"Light", "Scission"},
    },
    ["Black Halo"] = {
      hits = 2,
      class = "physical",
      ftp = {3.00, 7.25, 9.75},
      ftp_rep = false,
      wsc = { MND = 0.70, STR = 0.30 },
      sc = {"Fragmentation", "Compression"},
    },
  },

  staff = {
    ["Cataclysm"] = {
      hits = 1,
      class = "magical",
      element = "Dark",
      dstat = "INT",
      ftp = {2.75, 3.25, 3.75},
      ftp_rep = false,
      wsc = { INT = 0.30, MND = 0.30 },
      sc = {"Darkness", "Compression"},
    },
    ["Shattersoul"] = {
      hits = 1,
      class = "physical",
      ftp = {4.00, 7.00, 10.00},
      ftp_rep = false,
      wsc = { MND = 0.85 },
      sc = {"Gravitation", "Scission"},
    },
  },

  marksmanship = {
    ["Last Stand"] = {
      hits = 2,
      class = "ranged_physical",
      ftp = {2.00, 2.50, 3.00},
      ftp_rep = false,
      wsc = { AGI = 0.85 },
      sc = {"Light", "Fusion", "Reverberation"},
    },
    ["Coronach"] = {
      hits = 1,
      class = "ranged_physical",
      ftp = {3.00, 3.00, 3.00},
      ftp_rep = false,
      wsc = { AGI = 0.60 },
      sc = {"Darkness", "Fragmentation"},
    },
    ["Blast Shot"] = {
      hits = 2,
      class = "ranged_physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { AGI = 0.70 },
      sc = {"Transfixion"},
    },
    ["Heavy Shot"] = {
      hits = 1,
      class = "ranged_physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { AGI = 0.70 },
      sc = {"Detonation"},
    },
  },

  archery = {
    ["Jishnu's Radiance"] = {
      hits = 3,
      class = "ranged_physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = true,
      wsc = { DEX = 0.80 },
      crit_rate = {0.15, 0.30, 0.45},
      sc = {"Light", "Detonation"},
    },
    ["Apex Arrow"] = {
      hits = 1,
      class = "ranged_physical",
      ftp = {3.00, 4.25, 7.25},
      ftp_rep = false,
      wsc = { AGI = 0.60 },
      sc = {"Fragmentation", "Transfixion"},
    },
    ["Blast Arrow"] = {
      hits = 1,
      class = "ranged_physical",
      ftp = {2.00, 2.00, 2.00},
      ftp_rep = false,
      wsc = { STR = 0.20, AGI = 0.50 },
      sc = {"Induration", "Transfixion"},
    },
    ["Arching Arrow"] = {
      hits = 1,
      class = "ranged_physical",
      ftp = {2.00, 2.00, 2.00},
      ftp_rep = false,
      wsc = { STR = 0.20, AGI = 0.50 },
      sc = {"Fusion"},
    },
    ["Refulgent Arrow"] = {
      hits = 2,
      class = "ranged_physical",
      ftp = {3.00, 4.00, 5.00},
      ftp_rep = false,
      wsc = { STR = 0.60 },
      sc = {"Reverberation", "Transfixion"},
    },
    ["Empyreal Arrow"] = {
      hits = 1,
      class = "ranged_physical",
      ftp = {3.50, 5.00, 7.50},
      ftp_rep = false,
      wsc = { STR = 0.20, AGI = 0.50 },
      sc = {"Fusion", "Transfixion"},
    },
    ["Piercing Arrow"] = {
      hits = 1,
      class = "ranged_physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.20, AGI = 0.50 },
      sc = {"Reverberation", "Transfixion"},
    },
    ["Dulling Arrow"] = {
      hits = 1,
      class = "ranged_physical",
      ftp = {1.00, 1.00, 1.00},
      ftp_rep = false,
      wsc = { STR = 0.20, AGI = 0.50 },
      sc = {"Liquefaction", "Transfixion"},
    },
  },

}

return WEAPON_SKILLS
